---
title: 前端错误处理那些事
date: 2019-06-19 16:32:02
tags: ['javascript','错误处理']
categories: JavaScript
---
# 常见的js 错误捕获

## demo1
```
<script>
error;
console.log(1)
</script>

<script>
console.log(2)
</script>
```
上述的2是否会打印出来？ 
- 会执行 因为JavaScript标签都是独自执行的块

## 意料之中的错误

```
    try{
        //var error = "error";
        console.log(error)
    }catch(e){
        console.log(e);
    }
    这个时候可以捕获到错误
    try{
        setTimeout(()=>{
            error;
        })
    }catch(e){
        console.log("XXXX"，e)
    }
    异步的错误是无法catch的，下面介绍如何捕获
```
## 捕获异步的错误，意料之外的错误
```
    try{
        setTimeout(()=>{
            error;
        })
    }catch(e){
        console.log("XXXX"，e)
    }

    window.onerror = function(msg,url,row,col,error){
        console.log("捕获到错误",msg);
        //禁止页面报红
        return true;
    }
```
## html页面脚本的错误

```
<img src="./404.png">

window.addEventListener = function('error',(msg,url,row,col,error)=>{
    console.log("捕获到错误",msg);
    //禁止页面报红
    return false;
},true);
```

## Promise的错误
```
new Promise((resolve,reject)=>{
    reject("第一个error")
}).catch(function(err){
    console.log(err)
})


window.addEventListener("unhandledrejection",function(e){
    e.preventDefault();
    console.log(e.reason);
    return true;
})
new Promise((resolve,reject)=>{
    reject("第一个error")
})
Promise.resolve().then(()=>{
    throw "第三个错误"
})
Promise.reject("第二个错误")

```
## Fundebug
- nodejs版本容错
```
//全局的错误监控
process.on("uncaughtException",function(a){
    process.exit(1)
})

//针对promise的容错处理
process.on("unhandledRejection",function(a){

})
app.on("error",function(a){

})
```
sessionstack 记录生成dom树

navigator.sendBeacon("xx.php") 发送错误

zanePerfor 性能监控平台



